### ISSUE TITLE
What is the default text cell body font style?

### ISSUE THREAD

**Issue by degravek** [HappenApps/Quiver#1169]
What is the default text cell body font style?

**Comment by ylian** [comment]
```css
body {
  font-family: -apple-system, Helvetica, Arial, sans-serif;
  margin: 0;
  padding: 20px;
  color: #333;
  word-wrap: break-word;
}

.cell {
  margin: 5px 0;
  padding: 5px 10px;
  outline: none;
  min-height: 18px;
  overflow: hidden;
}

```
