### ISSUE TITLE
Lack default editor CSS styles for dark markdown-cell

### ISSUE THREAD

**Issue by binderclip** [HappenApps/Quiver#181]
![font-size](https://cloud.githubusercontent.com/assets/8187479/9933808/2625537e-5d80-11e5-9822-3f6bb79df6d3.png)

There only the `.light`'s, I can make a `.dark` copy but don't be sure of the other sets for dark theme.

```
.light .markdown-cell .ace_editor {
  background-color: #FFFFFF;
  color: #333;
  font-size: 16px;
  line-height: 1.5;
}
```

**Comment by ylian** [comment]
The dark style differs only in colors:

``` css
.dark .markdown-cell .ace_editor {
  color: #c7c7c7;
  background-color: #2b3137;
}
```

I will add these to the user CSS file.
