### ISSUE TITLE
change markdown font size in editor

### ISSUE THREAD

**Issue by joebnb** [HappenApps/Quiver#317]
in mac book air the markdown font was too small and no option to change it...

**Comment by rcrooks** [comment]
@joebnb you can modify this by editing the CSS under Styles in the Preferences. Not sure if you are referring to the font size in the editor or the preview, but you can change both.

**Comment by ghost** [comment]
@joebnb editing the CSS under Styles

``` css
.markdown-cell .ace_editor {
  background-color: #FFFFFF;
  color: #333;
  font-size: 17px;  /* change the font size you want */
  line-height: 1.5;
  font-family: "monaco";

}
```
