### ISSUE TITLE
请问如何 自定义 一些设置。

### ISSUE THREAD

**Issue by jiexishede** [HappenApps/Quiver#386]
我想在  markdown  里， 自定义  `代码` 的背景颜色 ， 请问应该如何 设置呢。。

` daima `  这个markdown 的backgroundColor.

**我想改变粗体大写的背景颜色**  请问如何 改变这个背景颜色？

**Comment by ylian** [comment]
``` css
code {
  background: red;
}

strong {
  background: red;
}
```
