### ISSUE TITLE
Cannot change font size of fenced code blocks in markdown cells (Preview mode)

### ISSUE THREAD

**Issue by lihuanglx** [HappenApps/Quiver#501]
In preview mode, the font size of fenced code blocks in markdown cells cannot be changed by setting the `font-size` of `markdown-cell` in css. I'm using 3.0.1 & OS X 10.11.3.

![image](https://cloud.githubusercontent.com/assets/7406791/13575328/50cf727e-e4c3-11e5-8b6a-20462265443b.png)

![image](https://cloud.githubusercontent.com/assets/7406791/13575341/5ab2a8e2-e4c3-11e5-88dc-99cc856de1ee.png)

**Comment by lihuanglx** [comment]
I can change it by uncommenting the `ace_line` selector in the second screenshot.

**Comment by philosopherdog** [comment]
Using the hint above I added this to preview:
```css
.markdown-cell .ace_line {
  font-family: "DejaVu Sans Mono";
  font-size: 18px;
}
```
