### ISSUE TITLE
Font for mathjax

### ISSUE THREAD

**Issue by chrispher** [HappenApps/Quiver#514]
I have used some setting for mathjax below.

``` css
/* **mathjax** */
.markdown-cell .MathJax {
  font-size: 11px;
  font-family: "Cambria Math";
  font-style: normal;
  color: red;
}
```

The `font-size` , `font-style` and `color`  worked for me, but the `font-family` did not. I have changed a lot of fonts, eg monaco...,but still not work.
