### ISSUE TITLE
Add support for font ligatures

### ISSUE THREAD

**Issue by bmario** [HappenApps/Quiver#725]
It would be great, if Quiver could support font ligatures, such as https://github.com/tonsky/FiraCode

**Comment by ylian** [comment]
Font ligatures are already supported. Simply install your favorite font, then set it in Preferences > Styles > CSS:

``` css
.code-cell .editor { font-family: "Fira Code"; }
```
