### ISSUE TITLE
Set cell background color

### ISSUE THREAD

**Issue by amir-mehler** [HappenApps/Quiver#729]
Simple as that. I don't even need many options.

It will make the search process and scanning of a note much faster.

Are you dyslexic? probably not. If you would be, you'd know how much colors can help.

Thanks.

**Comment by floq-design** [comment]
Under Preferences >  Styles you can set the background colour for cells using CSS.

**Editor Styles, for example:**

``` css
/**
* Text Cell
*/

.text-cell {
  background-color: #f00 !important;
}

/**
* Code Cell
*/

.code-cell .editor {
  background-color: #f00 !important;
}

/**
* LaTeX Cell
*/

.latex-cell .editor {
  background-color: #f00 !important;
}

/**
* Markdown Cell
*/

.markdown-cell .ace_editor {
  background-color: #f00;
}
```
