### ISSUE TITLE
Markdown rendering with HTML / CSS

### ISSUE THREAD

**Issue by stbraun** [HappenApps/Quiver#807]
Since updating to version 3.0.4 the rendering of Markdown (bold, italics) does not work anymore inside a `<div>`. This happens for preview and PDFs. 

I am using this in my notes to create colored text boxes:
`<div class="definition">*DEFINITION:* Some **text**</div>`

```css
div .definition {
  background: #bbddbb;
  color: #000000;
  padding: 5px;
  margin: 5px;
  border-radius: 5px;
  box-shadow: 2px 3px 0 0 #555555;
}
```

The asterisks are not evaluated inside of these boxes. It worked fine before the update, so it might have changed with the new Markdown engine.

I realize that using HTML in a Markdown text might be seen as abuse ;-) But having colored boxes for definitions etc. makes notes much more easy to read.
