### ISSUE TITLE
How to remove borders around the cells?

### ISSUE THREAD

**Issue by sauron918** [HappenApps/Quiver#859]
Help me to remove borders around the cells.

<img width="333" alt="2017-04-30 14 56 36" src="https://cloud.githubusercontent.com/assets/3842386/25564158/77ecbf1a-2db5-11e7-8155-6e3e6123c5e7.png">

I don't find how to do it in theme or styles.

**Comment by ylian** [comment]
I don't recommend removing the border. The UI would be confusing if you have more than one cell in the note.

**Comment by sauron918** [comment]
Usually I use only code blocks + markdown and they are visually different. So it's not a problem. How can I do that?

**Comment by ylian** [comment]
If you *really* want to do that, add the following to Preferences > Styles > Editor CSS:

```css
.cell.inEditMode {
  border-radius: 0;
  border: none;
  padding: 5px 10px;
}
```
