### ISSUE TITLE
Code cell cannot change fonts

### ISSUE THREAD

**Issue by john-x-jiang** [HappenApps/Quiver#879]
When I try to change the font in code cell, it doesn't work. The code language is python, and the font I want to change is Monaco. Thank you for your help!

**Comment by ylian** [comment]
Monaco should work fine.

Use this in Preferences > Styles > Editor CSS

```css
.code-cell .editor {
  font-size: 15px;
  font-family: Monaco;
}
```

**Comment by john-x-jiang** [comment]
It works. Thank you!

**Comment by WinCanton** [comment]
I doesn't work for me for some reasons..
Under `Preferences > Cells > Code Cells`, I use the theme `Solarized Dark` - and for some reasons the change as prescribed above does not work. Have I missed anything here?

All I want to do is to change the font size of the code-cell, particularly on the Preview.

**Comment by ylian** [comment]
The preview CSS is in a different file: Preferences > Styles > Preview CSS.

And it doesn't use editor so just this:

```css
.code-cell {
  font-size: 15px;
  font-family: Monaco;
}
```
