### ISSUE TITLE
change the the color in bold, Italian, underline... etc. in text cell 

### ISSUE THREAD

**Issue by zyyedi** [HappenApps/Quiver#888]
How can I do those under the preference setting? I know I have to modify the CSS setting, but how?

**Comment by ylian** [comment]
In Preferences > Styles > Editor CSS, add the following:

```css
.text-cell b {
  color: red;
}

.text-cell i {
  color: blue;
}

.text-cell u {
  color: green;
}
```
