### ISSUE TITLE
PDF Print - How to print the sytle like old version?

### ISSUE THREAD

**Issue by avno1** [HappenApps/Quiver#953]
> **Here is the newest version style. the only title, no tag information and baseline**

![2017-09-11 at 10 54](https://user-images.githubusercontent.com/26158957/30256759-8f97266c-96df-11e7-8510-74e49b539437.png)

> **Here is the old version style, have tag information and baseline**

![2017-09-11 at 10 56](https://user-images.githubusercontent.com/26158957/30256809-f11c0308-96df-11e7-9d25-4f5d38911b3a.png)

---

### Now I use the newest version, but have any way i can print the PDF like old version. it just look good on Chinese report. Have any on can give me a favor thanks.

**Comment by jonathan-morton** [comment]
I was getting ready to ask this same exact question. I prefer the old style

**Comment by ylian** [comment]
If you prefer the old style, add the following to the front of Preferences > Styles > Print CSS:

```css
body {
  width: 100%;
  line-height: 1.4;
}

#titlearea {
  border-bottom: 1px solid #ccc;
  padding: 10px 0;
}

#titlearea .title {
  font-size: 17px;
  margin: 11px 0;
  outline: none;
  text-align: left;
  min-height: 18px;
  font-weight: normal;
}

#tag-field {
  display: inline;
}
```

**Comment by avno1** [comment]
Thanks. It's working great. 👍

**Comment by jonathan-morton** [comment]
I noticed that when I used 
```css
body {
  width: 100%;
  line-height: 1.4;
}
```
When I exported to PDF, text would be cut off if I had large images. I adjusted the width to 95% and the problem seems to have gone away
